### ISSUE TITLE
Title rightBarButtonItem

### ISSUE THREAD

**Issue by Maxim-Zakopaylov** [alexhillc/AXPhotoViewer#15]
Hi, how i can change share bar button? 
I try this  
`photosViewController.overlayView.rightBarButtonItem = UIBarButtonItem(title: "delete", style: .plain, target: self, action: #selector(deletePhoto))`

But right button stay default.

**Comment by alexhillc** [comment]
Hi @Maxim-Zakopaylov, I’m in the middle of refactoring some initialization code to allow this to be changed before the view is loaded. A workaround for the time being is to call:
‘photosViewController.loadViewIfNecessary()’
before changing any overlayView properties.

This should be fixed in the next release.

**Comment by alexhillc** [comment]
Fixed in e334eb6d719017d2e4c5540e3a896323100c662f.
