### ISSUE TITLE
Crash on animated dismmissing controller.

### ISSUE THREAD

**Issue by ndarmancev** [alexhillc/AXPhotoViewer#28]
Lib version:
AXPhotoViewer (1.3.6)
AXStateButton (1.1.4)

crash at line 226 at file AXPhotosTransitionController 

photosViewController.currentPhotoViewController at the moment of dismiss have nil value,

`guard let imageView = photosViewController.currentPhotoViewController?.zoomingImageView.imageView as UIImageView? else {
            assertionFailure("No. ಠ_ಠ")
            return
        }`

P.S. It so funny and so "professional" have this smiles instead description text inside crash log?

**Comment by alexhillc** [comment]
Hey bud, sorry you're having issues. Those assertions are there because they should never happen.
I can take a look at the root cause of this problem, but I would advise against assuming professionalism on Github. A lot of people (such as myself) make libraries like this because we are bored, and find uses for it in other projects that we work on.

**Comment by ndarmancev** [comment]
Good day Alex, thank you for this library. I understood, but at least this comments looks really strange.
